### ISSUE TITLE
Publish to packagist

### ISSUE THREAD

**Issue by clind922** [rmuit/sharpspring-restapi#3]
Would you be so kind as to make this package available on https://packagist.org/ so to be able to be installed via composer?

Kind regards

**Comment by freak3dot** [comment]
In case anyone stumbles upon this in the future. This package currently appears to be on Packagist.

https://packagist.org/packages/wyz/sharpspring-restapi

**Comment by rmuit** [comment]
Sorry, I wasn't watching my own repository so I didn't see this comment. Will try to do better / will go through my repositories now.
